// Copies the compiled ABIs from contracts/out into packages/shared/src/abi.ts as `as const` arrays,
// so viem infers full types in the web app. Run after `forge build`: `pnpm shared:abi`.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const contracts = [
  ["patchedMarketAbi", "PatchedMarket.sol/PatchedMarket.json"],
  ["patchReceiptAbi", "PatchReceipt.sol/PatchReceipt.json"],
  ["testUsdAbi", "TestUSD.sol/TestUSD.json"],
  ["patchAutoBidderAbi", "PatchAutoBidder.sol/PatchAutoBidder.json"],
];

let out = "// Generated by packages/shared/scripts/export-abi.mjs — do not edit by hand.\n";
for (const [name, file] of contracts) {
  const { abi } = JSON.parse(readFileSync(join(root, "contracts", "out", file), "utf8"));
  out += `\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}
writeFileSync(join(root, "packages", "shared", "src", "abi.ts"), out);
console.log("wrote packages/shared/src/abi.ts");
